### PR TITLE
Add four performance curves for DX Cooling Coil taken from Carrier document to update unitary.pxt

### PR DESCRIPTION
**Pull request by wsjsxn**
Energy Solutions collected the catalog data from various HP manufacturers and add four performance curves for DX Cooling Coil taken from Carrier document https://www.shareddocs.com/hvac/docs/1009/Public/06/25VNA4-02PD.pdf model 25VNA436. The goal is to include these performance curves in the DEER prototype library and let the users to choose them for their modeling purpose.

### CODE REVIEW

**Comment by amine-lazrak** [comment]
Thank you for your efforts on the new feature. Before merging it into the main branch, we have a few requests for changes:

**Pull Request (PR) Template:**
Please ensure you follow the [PR template](https://github.com/sound-data/DEER-Prototypes-EnergyPlus/blob/main/pull_request_template.md) directions that appear when creating a new PR. We ask contributors to go through and select each required step in the template and confirm its completion.

**Completeness of Performance Curves:**
The performance curves submitted are for a variable speed system, and there are two modeling options to consider. Option 1 involves using a [multi-speed EnergyPlus object](https://bigladdersoftware.com/epx/docs/22-2/input-output-reference/group-heating-and-cooling-coils.html#coilcoolingdxmultispeed), requiring curves for each speed level. Currently, it seems only one set of curves for one speed is provided. Option 2 involves using the [variable speed object](https://bigladdersoftware.com/epx/docs/22-2/input-output-reference/group-heating-and-cooling-coils.html#coilcoolingdxvariablespeed), necessitating multiple curves for different speeds. The variable speed model is not implemented in the unitary.pxt template. If you choose to add it, we recommend exploring [this package](https://github.com/bigladder/resdx/blob/main/examples/neep-examples.py) for performance tables generation. If you're not following these two options, we would appreciate more context and justification for the chosen approach in modeling a variable speed HP with a single set of curves.

**Lack of Parameterization:**
The curves were added without parameterization, making it challenging for users to select between curves using a parameter. We expect any new addition to seamlessly integrate into the modeling framework, requiring minimal adjustments on our end. Please review how existing curves are parameterized (e.g., see the parameter [dx_type](https://github.com/sound-data/DEER-Prototypes-EnergyPlus/blob/0b8074907073ba52c795ba4db4607619cae8e860/templates/energyplus/templates/system/unitary.pxt#L91C8-L91C9)).

**Missing Simulation Results Examples:**
The pull request lacks simulation result examples (of your choice), as specified in the [pull request template](https://github.com/sound-data/DEER-Prototypes-EnergyPlus/blob/main/pull_request_template.md#:~:text=For%20a%20new%20feature%20or%20bug%2C%20demonstrate%20the%20impact%20on%20energy%20consumption%20for%20selected%20cases%20with%20justification%20using%20plots%20and%20descriptions.). Your inclusion of these examples will greatly assist in the review process.

**Comment by wsjsxn** [comment]
Here is the list of the requirements for PR author from pull request template. Where is the requirement for simulation result examples? 

PR Author
 Craft a succinct title that effectively encapsulates the essence of the pull request, providing a general overview of the proposed changes.
 Label the PR with at least one of the following: New Measure, Bug, or Feature.
 Provide a concise description of the measure, bug, or feature. Submit one PR per measure.
 For a new measure, attach a workbook named DEER_EnergyPlus_Modelkit_Measure_list_working.xlsx, containing only rows used for post-processing the measure.
 Add comments in the code when necessary to facilitate the review process.
 Add a comment before the added code, including the author's full name, company, and specifying if it's a bug fix, new measure, or feature.
 For a new feature or bug, demonstrate the impact on energy consumption for selected cases with justification using plots and descriptions.
 For a new measure, add a summary table showing total energy consumption per simulated case.

**Comment by wsjsxn** [comment]
I used COIL:COOLING:DX:MULTISPEED with 4 speeds to simulate the variable speed heat pump with Carrier model 25VNA436. For variable speed heat pump, the manufacture's catalogs don't provide the performance data of the DX coil at different speeds. Therefore, I have to use the same set of the performance curves for each speed level.

**Comment by amine-lazrak** [comment]
That's one approach if you find it reasonable. Does the manufacturer provide minimum and maximum values at specific rating conditions? If you can identify the system you want to model among those listed [here](https://ashp.neep.org/#!/product_list/), then I recommend using this [tool ](https://github.com/bigladder/resdx/tree/main)to build the curves at different speeds.

#### Example:
For instance, if you want to model this [system](https://ashp.neep.org/#!/product/95190/7/25000/95/7500/0///0), you would need to extract the data from the table on that page and input it into the Python tool. You can find an example [here](https://github.com/bigladder/resdx/blob/13f14b1daf633accb7c1945f6469d6cd57854290/examples/neep-examples.py#L57). After running the package, a new folder named output will be created, containing the IDF of the system you want to model with all performance data in tables that can be directly referenced in the variable-speed EnergyPlus object.

**Comment by wsjsxn** [comment]
Thanks for your info on resdx github repo for curve generation and I will
take a look at it.
Best,

Shaojie Wang



Ph.D., PE, LEED AP

**Comment by amine-lazrak** [comment]
@wsjsxn Are you planning to make more changes to this pull request? Let us know when this is ready to be reviewed.

**Comment by wsjsxn** [comment]
@amine-lazrak I have completed all the changes for this pull request. You can start to review this pull request. Thanks,

**Comment by amine-lazrak** [comment]
@wsjsxn This PR branch is [83 commits behind](https://github.com/wsjsxn/Performance_Curve/tree/main#:~:text=This%20branch%20is,.) the `main` branch. Could you please update your branch so that it's up to date with `main`? I'll review it right after.

**Comment by wsjsxn** [comment]
I have updated my branch with all the changes from the main branch. Thanks

**Comment by amine-lazrak** [comment]
@wsjsxn The newly added curves are identical to the existing ones when `dx_type` equals `SPLIT`. Was this intentional? If so, are you suggesting changing the name of the system curves? In that case, I wonder if we should add an if statement that defaults to `SPLIT` when users choose `Carrier25VNA436` instead of adding the entire curves again.

**Comment by wsjsxn** [comment]
I revised the coefficients for newly added cooling/heating capacity and EIR performance curves

**Comment by amine-lazrak** [comment]
Closed for now; may revisit if relevant in the future.

**Pull request closed without merging**
