### PR TITLE
SWHC004 Space Heating Boiler (residential subset)

### PR DESCRIPTION
**Pull request by simularis**
# Pull Request (PR) Description

This pull request is to include a measure setup for SWHC004. For this measure, we have made the following setup:
- Added boilers and hydronic loop to residential MFm (rNCHW only)
- Added fluid type parameters in prototypes and templates to implement steam boiler options. Note that some models include two boilers, so we have included multiple parameters where that seemed appropriate.
- Inputs include parameters necessary to trigger boiler type configurations
- Inputs include boiler efficiency levels
- Scripts for extracting boiler auto-sizing results and inserting the results into post-process output files.

### PR Author
- [x] Craft a succinct title that effectively encapsulates the essence of the pull request, providing a general overview of the proposed changes.
- [x] Provide a concise description of the measure, bug, or feature. Submit one PR per measure.
- [x] For a new measure, attach a workbook named DEER_EnergyPlus_Modelkit_Measure_list_working.xlsx, containing only rows used for post-processing the measure.
- [x] Add comments in the code when necessary to facilitate the review process.
- [x] Add a comment before the added code, including the author's full name, company, and specifying if it's a bug fix, new measure, or feature.
- [ ] For a new feature or bug, demonstrate the impact on energy consumption for selected cases with justification using plots and descriptions.
- [ ] For a new measure, add a summary table showing total energy consumption per simulated case.
### PR Reviewer
- [ ] Label the PR with at least one of the following: New Measure, Bug, or Feature (author comment: this option is not available to us).
- [ ] Conduct a thorough code review.
- [ ] If the branch is behind the main, merge the branch locally to check for potential conflicts.
- [ ] If a bug, locally reproduce it and compare energy consumptions before and after.
- [ ] Explore creative ways to stress-test the code.
- [ ] Locally check the error file and other outputs.

### CODE REVIEW

**Comment by amine-lazrak** [comment]
@simularis Could you please update your pull request branch to incorporate the latest changes from the main branch? This will help ensure that any conflicts are resolved before we proceed with the review.

**Comment by simularis** [comment]
Updated to incorporate the latest changes from the main branch.

**Comment by lyt5410** [comment]
I did test run after Amine's request. I have the same SQLite fatal error (only for some runs). I tested CZ01, 02 and 03. The fatal error happened for 2 of the baseline (AFUE83, AFUE84) and the AFUE85.3 Msr case. Other cases (AFUE85, 93, 94) ran without error.
@amine-lazrak @simularis

**Comment by simularis** [comment]
Renamed the boiler prototypes per Amine's comment.

**Comment by simularis** [comment]
Regarding the error message mentioned above, we had not encountered that. Thank you for testing. I am assuming that message is coming from Modelkit, rather than from EnergyPlus or the Python data transformation script? I wonder if it may be related to path length, e.g. if the file name is too long.

**Comment by amine-lazrak** [comment]
> Regarding the error message mentioned above, we had not encountered that. Thank you for testing. I am assuming that message is coming from Modelkit, rather than from EnergyPlus or the Python data transformation script? I wonder if it may be related to path length, e.g. if the file name is too long.

I'm not completely certain, but we'll look into it to confirm. We've encountered issues with Windows file names length before, but the error message was different then. This current error seems unrelated to Modelkit because others ([1](https://unmethours.com/question/36452/fatal-the-sqlite-database-failed-to-open/),[2](https://discourse.ladybug.tools/t/the-sqlite-database-failed-to-open/15394)) using different tools have reported the same problem. Thank you for the update.

**Comment by simularis** [comment]
Thanks for sharing info about that error. It would be helpful to collect the folder from a simulation instance that failed, so we could examine the sqlite error log and sql file.

Come to think of it, I have had some problems getting BEopt to run with a high number of threads. I wonder if that is related.

**Pull request merged**
